"""Add transaction_type field

Revision ID: 91bbe4c68e57
Revises: c003e8b3317a
Create Date: 2025-10-21 20:21:55.166733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bbe4c68e57'
down_revision = 'c003e8b3317a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=20), nullable=False, server_default='expense'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
